global:
  scrape_interval: 1s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    honor_labels: true
    static_configs:
      - targets: ["host.docker.internal:8873", "host.docker.internal:8875"]
