apiVersion: skaffold/v2beta29
kind: Config

build:
  artifacts:
  - image: public.ecr.aws/k2z7t6t6/metaplex-rpc-load-generator
    context: .
    docker:
      dockerfile: Load.Dockerfile
  - image: public.ecr.aws/k2z7t6t6/metaplex-rpc-api
    context: .
    docker:
      dockerfile: Api.Dockerfile
  - image: public.ecr.aws/k2z7t6t6/metaplex-rpc-ingest
    context: .
    docker:
      dockerfile: Ingest.Dockerfile
  - image: public.ecr.aws/k2z7t6t6/metaplex-rpc-migrator
    context: .
    docker:
      dockerfile: Migrator.Dockerfile
  - image: public.ecr.aws/k2z7t6t6/metaplex-rpc-proxy
    context: .
    docker:
      dockerfile: Proxy.Dockerfile
deploy:
  helm:
    releases:
    - name: das-ingester
      chartPath: helm/ingest
      valuesFiles:
      - ./helm/ingest/values.yaml
      setValues:
        image: public.ecr.aws/k2z7t6t6/metaplex-rpc-ingest
        loadImage: public.ecr.aws/k2z7t6t6/metaplex-rpc-load-generator
        migratorImage: public.ecr.aws/k2z7t6t6/metaplex-rpc-migrator
      setValueTemplates:
        ingest.db_url: '{{.DATABASE_URL}}'
        ingest.redis_url: '{{.REDIS_URL}}'
        ingest.rpc_url: '{{.RPC_URL}}'
        load.rpc_url: '{{.RPC_URL}}'
        load.seed: '{{.LOAD_SEED}}'
        metrics.data_dog_api_key: '{{.DATA_DOG_API}}'
        migrator.image: 'public.ecr.aws/k2z7t6t6/metaplex-rpc-migrator:{{.DEPLOY_VERSION}}'
    - name: das-api
      chartPath: helm/api
      valuesFiles:
      - ./helm/api/values.yaml
      setValues:
        image: public.ecr.aws/k2z7t6t6/metaplex-rpc-api
        proxy.image: public.ecr.aws/k2z7t6t6/metaplex-rpc-proxy
      setValueTemplates:
        api.db_url: '{{.DATABASE_URL}}'
        api.redis_url: '{{.REDIS_URL}}'
        metrics.data_dog_api_key: '{{.DATA_DOG_API}}'
        proxy.auth: '{{.PROXY_AUTH}}'
        proxy.host: '{{.PROXY_HOST}}'

profiles:
- name: ci
  patches:
    - op: add
      path: /build/tagPolicy
      value:
        envTemplate:
          template: '{{.DEPLOY_VERSION}}'

- name: devnet
  patches:
  - op: add
    path: /deploy/helm/releases/0/valuesFiles/1
    value: ./helm/ingester-values-devnet.yaml
  - op: add
    path: /deploy/helm/releases/1/valuesFiles/1
    value: ./helm/api-values-devnet.yaml
