{
 "title": "READ API",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "ACCOUNT UPDATE PROCESSING TIME",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "stats.timers.das_ingester.ingester.account_proc_time.mean_90"
    }
   ]
  },
  {
   "title": "ACCOUNT EVENTS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "aggregate(seriesByTag('name=stats_counts.plerkle.account_seen_event'), 'sum')"
    }
   ]
  },
  {
   "title": "TXN EVENTS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "aggregate(seriesByTag('name=stats_counts.plerkle.transaction_seen_event'), 'sum')"
    }
   ]
  }
 ]
}