//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use super::generated::sea_orm_active_enums::WhitelistMintMode;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "candy_guard_group"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub id: i64,
    pub label: Option<String>,
    pub candy_guard_id: Vec<u8>,
    pub whitelist_mode: Option<WhitelistMintMode>,
    pub whitelist_mint: Option<Vec<u8>>,
    pub whitelist_presale: Option<bool>,
    pub whitelist_discount_price: Option<i32>,
    pub bot_tax_lamports: Option<i32>,
    pub bot_tax_last_instruction: Option<bool>,
    pub live_date: Option<i32>,
    pub third_party_signer_key: Option<Vec<u8>>,
    pub nft_payment_destination: Option<Vec<u8>>,
    pub nft_payment_required_collection: Option<Vec<u8>>,
    pub allow_list_merkle_root: Option<Vec<u8>>,
    pub mint_limit_id: Option<i32>,
    pub mint_limit_limit: Option<i32>,
    pub gatekeeper_network: Option<Vec<u8>>,
    pub gatekeeper_expire_on_use: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Label,
    CandyGuardId,
    WhitelistMode,
    WhitelistMint,
    WhitelistPresale,
    WhitelistDiscountPrice,
    BotTaxLamports,
    BotTaxLastInstruction,
    LiveDate,
    ThirdPartySignerKey,
    NftPaymentDestination,
    NftPaymentRequiredCollection,
    AllowListMerkleRoot,
    MintLimitId,
    MintLimitLimit,
    GatekeeperNetwork,
    GatekeeperExpireOnUse,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    CandyGuard,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigInteger.def(),
            Self::Label => ColumnType::String(Some(50u32)).def().null(),
            Self::CandyGuardId => ColumnType::Binary.def(),
            Self::WhitelistMode => WhitelistMintMode::db_type().null(),
            Self::WhitelistMint => ColumnType::Binary.def().null(),
            Self::WhitelistPresale => ColumnType::Boolean.def().null(),
            Self::WhitelistDiscountPrice => ColumnType::Integer.def().null(),
            Self::BotTaxLamports => ColumnType::Integer.def().null(),
            Self::BotTaxLastInstruction => ColumnType::Boolean.def().null(),
            Self::LiveDate => ColumnType::Integer.def().null(),
            Self::ThirdPartySignerKey => ColumnType::Binary.def().null(),
            Self::NftPaymentDestination => ColumnType::Binary.def().null(),
            Self::NftPaymentRequiredCollection => ColumnType::Binary.def().null(),
            Self::AllowListMerkleRoot => ColumnType::Binary.def().null(),
            Self::MintLimitId => ColumnType::Integer.def().null(),
            Self::MintLimitLimit => ColumnType::Integer.def().null(),
            Self::GatekeeperNetwork => ColumnType::Binary.def().null(),
            Self::GatekeeperExpireOnUse => ColumnType::Boolean.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::CandyGuard => Entity::belongs_to(super::candy_guard::Entity)
                .from(Column::CandyGuardId)
                .to(super::candy_guard::Column::Id)
                .into(),
        }
    }
}

impl Related<super::candy_guard::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CandyGuard.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
