//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use super::sea_orm_active_enums::OwnerType;
use super::sea_orm_active_enums::RoyaltyTargetType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "candy_machine_state"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub id: i64,
    pub candy_machine_data_id: i64,
    pub authority: Vec<u8>,
    pub wallet: Vec<u8>,
    pub token_mint: Option<Vec<u8>>,
    pub items_redeemed: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    CandyMachineDataId,
    Authority,
    Wallet,
    TokenMint,
    ItemsRedeemed,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Vec<u8>;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    CandyMachineData,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigInteger.def(),
            Self::CandyMachineDataId => ColumnType::BigInteger.def().null(),
            Self::Authority => ColumnType::Binary.def(),
            Self::Wallet => ColumnType::Binary.def(),
            Self::TokenMint => ColumnType::Binary.def().null(),
            Self::ItemsRedeemed => ColumnType::Integer.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::CandyMachineData => Entity::belongs_to(super::candy_machine_data::Entity)
                .from(Column::CandyMachineDataId)
                .to(super::candy_machine_data::Column::Id)
                .into(),
        }
    }
}

impl Related<super::candy_machine_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CandyMachineData.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
