//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "candy_machine_freeze"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub id: i64,
    pub candy_machine: Pubkey,
    pub allow_thaw: bool,
    pub frozen_count: u64,
    pub mint_start: Option<i64>,
    pub freeze_time: i64,
    pub freeze_fee: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    CandyMachine,
    AllowThaw,
    FrozenCount,
    MintStart,
    FreezeTime,
    FreezeFee,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Vec<u8>;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    CandyMachineData,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigInteger.def(),
            Self::CandyMachine => ColumnType::Binary.def(),
            Self::AllowThaw => ColumnType::Boolean.def(),
            Self::FrozenCount => ColumnType::Integer.def(),
            Self::MintStart => ColumnType::Integer.def().null(),
            Self::FreezeTime => ColumnType::Integer.def(),
            Self::FreezeFee => ColumnType::Integer.def(),
        }
    }
}

impl ActiveModelBehavior for ActiveModel {}
