//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use super::generated::sea_orm_active_enums::EndSettingType;
use super::generated::sea_orm_active_enums::WhitelistMintMode;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "candy_machine_data"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub id: i64,
    pub uuid: Option<String>,
    pub price: Option<i64>,
    pub symbol: String,
    pub seller_fee_basis_points: i16,
    pub max_supply: i64,
    pub is_mutable: bool,
    pub retain_authority: Option<bool>,
    pub go_live_date: Option<i64>,
    pub items_available: i64,
    pub candy_machine_id: Vec<u8>,
    pub whitelist_mode: Option<WhitelistMintMode>,
    pub whitelist_mint: Option<Vec<u8>>,
    pub whitelist_presale: Option<bool>,
    pub whitelist_discount_price: Option<i64>,
    pub config_line_settings_prefix_name: Option<String>,
    pub config_line_settings_name_length: Option<i32>,
    pub config_line_settings_prefix_uri: Option<String>,
    pub config_line_settings_uri_length: Option<i32>,
    pub config_line_settings_is_sequential: Option<bool>,
    pub gatekeeper_network: Option<Vec<u8>>,
    pub gatekeeper_expire_on_use: Option<bool>,
    pub end_setting_number: Option<i64>,
    pub end_setting_type: Option<EndSettingType>,
    pub hidden_settings_name: Option<String>,
    pub hidden_settings_uri: Option<String>,
    pub hidden_settings_hash: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Uuid,
    Price,
    Symbol,
    SellerFeeBasisPoints,
    MaxSupply,
    IsMutable,
    RetainAuthority,
    GoLiveDate,
    ItemsAvailable,
    CandyMachineId,
    WhitelistMode,
    WhitelistMint,
    WhitelistPresale,
    WhitelistDiscountPrice,
    ConfigLineSettingsPrefixName,
    ConfigLineSettingsNameLength,
    ConfigLineSettingsPrefixUri,
    ConfigLineSettingsUriLength,
    ConfigLineSettingsIsSequential,
    GatekeeperNetwork,
    GatekeeperExpireOnUse,
    EndSettingNumber,
    EndSettingType,
    HiddenSettingsName,
    HiddenSettingsUri,
    HiddenSettingsHash,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    CandyMachine,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigInteger.def(),
            Self::Uuid => ColumnType::String(Some(6u32)).def().null(),
            Self::Price => ColumnType::BigInteger.def().null(),
            Self::Symbol => ColumnType::String(Some(10u32)).def(),
            Self::SellerFeeBasisPoints => ColumnType::SmallInteger.def(),
            Self::MaxSupply => ColumnType::BigInteger.def(),
            Self::IsMutable => ColumnType::Boolean.def(),
            Self::RetainAuthority => ColumnType::Boolean.def().null(),
            Self::GoLiveDate => ColumnType::BigInteger.def().null(),
            Self::ItemsAvailable => ColumnType::BigInteger.def(),
            Self::CandyMachineId => ColumnType::Binary.def(),
            Self::WhitelistMode => WhitelistMintMode::db_type().null(),
            Self::WhitelistMint => ColumnType::Binary.def().null(),
            Self::WhitelistPresale => ColumnType::Boolean.def().null(),
            Self::WhitelistDiscountPrice => ColumnType::BigInteger.def().null(),
            Self::ConfigLineSettingsPrefixName => ColumnType::String(Some(10u32)).def().null(),
            Self::ConfigLineSettingsNameLength => ColumnType::Integer.def().null(),
            Self::ConfigLineSettingsPrefixUri => ColumnType::String(Some(10u32)).def().null(),
            Self::ConfigLineSettingsUriLength => ColumnType::Integer.def().null(),
            Self::ConfigLineSettingsIsSequential => ColumnType::Boolean.def().null(),
            Self::GatekeeperNetwork => ColumnType::Binary.def().null(),
            Self::GatekeeperExpireOnUse => ColumnType::Boolean.def().null(),
            Self::EndSettingNumber => ColumnType::BigInteger.def().null(),
            Self::EndSettingType => EndSettingType::db_type().null(),
            Self::HiddenSettingsName => ColumnType::String(Some(50u32)).def().null(),
            Self::HiddenSettingsUri => ColumnType::String(Some(200u32)).def().null(),
            Self::HiddenSettingsHash => ColumnType::Binary.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::CandyMachine => Entity::belongs_to(super::candy_machine::Entity)
                .from(Column::CandyMachineId)
                .to(super::candy_machine::Column::Id)
                .into(),
        }
    }
}

impl Related<super::candy_machine::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CandyMachine.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
